// artistsData.js
export const artists = [
    // Concerts
    {
      id: 1,
      name: "Rock Band",
      discography: ["Album 1", "Album 2", "Album 3"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 1,
    },
    {
      id: 2,
      name: "Jazz Masters",
      discography: ["Smooth Jazz", "Jazz Nights", "Jazz Vibes"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 1,
    },
    // Festivals
    {
      id: 3,
      name: "Festival Fever",
      discography: ["Festival Hits", "Summer Beats", "Party Time"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 2,
    },
    {
      id: 4,
      name: "Cultural Vibes",
      discography: ["World Music", "Cultural Fest", "Global Sounds"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 2,
    },
    // Music Tours
    {
      id: 5,
      name: "Touring Band",
      discography: ["Tour Live", "On the Road", "City Stops"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 3,
    },
    {
      id: 6,
      name: "Road Show",
      discography: ["Live at Venue", "Roadside Concerts", "Highway Tunes"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 3,
    },
    // Recitals
    {
      id: 7,
      name: "Classical Recitalist",
      discography: ["Sonatas", "Classical Evenings", "Piano Pieces"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 4,
    },
    {
      id: 8,
      name: "Violin Virtuoso",
      discography: ["Violin Masterpieces", "String Quartets", "Orchestral Works"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 4,
    },
    // Open Mic Nights
    {
      id: 9,
      name: "Open Mic Star",
      discography: ["Live at Open Mic", "Acoustic Sessions", "Mic Night"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 5,
    },
    {
      id: 10,
      name: "Mic Master",
      discography: ["Master of Mic", "Open Night Hits", "Live Performances"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 5,
    },
    // Battle of the Bands
    {
      id: 11,
      name: "Rock Battle",
      discography: ["Battle Royale", "Band Clash", "Live Battle"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 6,
    },
    {
      id: 12,
      name: "Band Clash",
      discography: ["Clash of Bands", "Battle of Beats", "Final Showdown"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 6,
    },
    // DJ Sets
    {
      id: 13,
      name: "DJ Awesome",
      discography: ["Remix Hits", "Club Nights", "Dance Beats"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 7,
    },
    {
      id: 14,
      name: "DJ Spin",
      discography: ["Spin Sessions", "Electro Beats", "Night Club"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 7,
    },
    // Operas
    {
      id: 15,
      name: "Opera Stars",
      discography: ["Opera Gala", "Grand Performances", "Classic Operas"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 8,
    },
    {
      id: 16,
      name: "Classic Opera",
      discography: ["Opera Highlights", "Evening of Opera", "Famous Arias"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 8,
    },
    // Musicals
    {
      id: 17,
      name: "Broadway Stars",
      discography: ["Musical Hits", "Broadway Nights", "Stage Performances"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 9,
    },
    {
      id: 18,
      name: "Musical Legends",
      discography: ["Legendary Musicals", "Stage Classics", "Performance Nights"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 9,
    },
    // Symphonies/Orchestral Concerts
    {
      id: 19,
      name: "Orchestra Symphony",
      discography: ["Symphonic Masterpieces", "Orchestral Performances", "Evening Concerts"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 10,
    },
    {
      id: 20,
      name: "Philharmonic Orchestra",
      discography: ["Philharmonic Nights", "Classical Symphony", "Grand Concerts"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 10,
    },
    // Jam Sessions
    {
      id: 21,
      name: "Jam Session Band",
      discography: ["Live Jams", "Jam Night", "Spontaneous Sessions"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 11,
    },
    {
      id: 22,
      name: "Improvisation Group",
      discography: ["Improvised Jams", "Live Performances", "Music Sessions"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 11,
    },
    // Tribute Shows
    {
      id: 23,
      name: "Tribute Band",
      discography: ["Tribute to Rock", "Classic Hits", "Legendary Tunes"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 12,
    },
    {
      id: 24,
      name: "Memory Lane",
      discography: ["Nostalgic Hits", "Memory Lane Live", "Classic Tribute"],
      socialMediaLinks: {
        twitter: "/",
        instagram: "/",
        youtube: "/",
        tiktok: "/",
        email: "/",
        facebook: "/",
      },
      image: "/person.jpeg",
      eventId: 12,
    },
  ];