export const meetupsData = [
    {
        id: 1,
        title: "Comic Convention 2025",
        type: "Convention",
        date: "March 15, 2025",
        time: "10:00 AM",
        location: "Metro Convention Center",
        price: 45.99,
        availableSeats: 200,
        image: "conventions.jpg",
        description: "Join fellow comic enthusiasts for a day of panels, cosplay, and artist meet-and-greets."
    },
    {
        id: 2,
        title: "Tech Startup Summit",
        type: "Seminar",
        date: "April 2, 2025",
        time: "9:00 AM",
        location: "Innovation Hub",
        price: 149.99,
        availableSeats: 150,
        image: "conventions.jpg",
        description: "Learn from successful entrepreneurs and network with industry leaders."
    },
    {
        id: 3,
        title: "K-Pop Star Fan Meet",
        type: "Fan Meet",
        date: "March 20, 2025",
        time: "5:00 PM",
        location: "Star Arena",
        price: 89.99,
        availableSeats: 100,
        image: "exhibition.jpeg",
        description: "Exclusive meet and greet with your favorite K-pop stars."
    },
    {
        id: 4,
        title: "Authors Convention",
        type: "Convention",
        date: "April 10, 2025",
        time: "11:00 AM",
        location: "Central Library",
        price: 35.99,
        availableSeats: 250,
        image: "conventions.jpg",
        description: "Book signings, writing workshops, and panel discussions with renowned authors."
    },
    {
        id: 5,
        title: "Blockchain & Crypto Workshop",
        type: "Seminar",
        date: "May 5, 2025",
        time: "2:00 PM",
        location: "FinTech Hub",
        price: 199.99,
        availableSeats: 120,
        image: "conventions.jpg",
        description: "Deep dive into blockchain technology and cryptocurrency trends with industry leaders."
    },
    {
        id: 6,
        title: "AI and Machine Learning Bootcamp",
        type: "Workshop",
        date: "June 12, 2025",
        time: "10:00 AM",
        location: "Tech Academy",
        price: 299.99,
        availableSeats: 50,
        image: "exhibition.jpeg",
        description: "A hands-on workshop on AI and ML applications with real-world case studies."
    },
    {
        id: 7,
        title: "Anime & Manga Artist Meet",
        type: "Fan Meet",
        date: "July 20, 2025",
        time: "3:00 PM",
        location: "Otaku Hub",
        price: 65.99,
        availableSeats: 75,
        image: "conventions.jpg",
        description: "Meet famous anime and manga artists and get exclusive signed artwork."
    },
    {
        id: 8,
        title: "International Food Tasting",
        type: "Cultural Event",
        date: "August 8, 2025",
        time: "7:00 PM",
        location: "Gourmet Plaza",
        price: 55.99,
        availableSeats: 150,
        image: "tournaments.jpeg",
        description: "A culinary journey through various international cuisines with expert chefs."
    },
    {
        id: 9,
        title: "Professional Networking Night",
        type: "Networking",
        date: "September 15, 2025",
        time: "6:00 PM",
        location: "Business Hub",
        price: 79.99,
        availableSeats: 100,
        image: "conventions.jpg",
        description: "Connect with professionals from different industries in an exclusive networking session."
    },
    {
        id: 10,
        title: "Photography Masterclass",
        type: "Master Class",
        date: "October 10, 2025",
        time: "4:00 PM",
        location: "Creative Studio",
        price: 120.99,
        availableSeats: 60,
        image: "exhibition.jpeg",
        description: "A masterclass on professional photography techniques with hands-on practice."
    },
    {
        id: 11,
        title: "Esports Championship Meet & Greet",
        type: "Gaming Tournament",
        date: "November 5, 2025",
        time: "5:30 PM",
        location: "Game Arena",
        price: 49.99,
        availableSeats: 90,
        image: "tournaments.jpeg",
        description: "Meet top esports players and get insider tips on competitive gaming."
    },
    {
        id: 12,
        title: "VIP Behind-the-Scenes Movie Tour",
        type: "VIP Experience",
        date: "December 1, 2025",
        time: "12:00 PM",
        location: "Hollywood Studios",
        price: 249.99,
        availableSeats: 30,
        image: "exhibition.jpeg",
        description: "An exclusive tour behind the scenes of a major movie production."
    },
    {
        id: 13,
        title: "Women in Tech Leadership Summit",
        type: "Seminar",
        date: "January 18, 2026",
        time: "9:00 AM",
        location: "Innovation Center",
        price: 99.99,
        availableSeats: 120,
        image: "conventions.jpg",
        description: "A conference highlighting women leaders in the tech industry."
    },
    {
        id: 14,
        title: "Exclusive Collectors' Fair",
        type: "Convention",
        date: "February 25, 2026",
        time: "11:00 AM",
        location: "Exhibition Hall",
        price: 39.99,
        availableSeats: 200,
        image: "tournaments.jpeg",
        description: "A special event for collectors featuring rare and exclusive items."
    },
    {
        id: 15,
        title: "Language Exchange Meetup",
        type: "Cultural Event",
        date: "March 5, 2026",
        time: "4:30 PM",
        location: "Global Café",
        price: 25.99,
        availableSeats: 100,
        image: "conventions.jpg",
        description: "Practice languages and engage with diverse cultures in an interactive environment."
    },
    {
        id: 16,
        title: "iPhone 17 Launch Event",
        type: "Product Launch",
        date: "March 15, 2026",
        time: "10:00 AM",
        location: "Tech Center",
        price: 199.99,
        availableSeats: 300,
        image: "exhibition.jpeg",
        description: "Be among the first to experience the latest iPhone with exclusive hands-on demos."
    },
    {
        id: 17,
        title: "Contemporary Art Exhibition Opening",
        type: "Art Exhibition",
        date: "March 20, 2026",
        time: "6:00 PM",
        location: "Modern Art Gallery",
        price: 45.99,
        availableSeats: 150,
        image: "conventions.jpg",
        description: "Opening night of contemporary art exhibition featuring local and international artists."
    },
    {
        id: 18,
        title: "Virtual Reality Gaming Tournament",
        type: "Gaming Tournament",
        date: "March 25, 2026",
        time: "2:00 PM",
        location: "VR Arena",
        price: 75.99,
        availableSeats: 64,
        image: "tournaments.jpeg",
        description: "Compete in the latest VR games and win exclusive prizes."
    },
    {
        id: 19,
        title: "Quantum Computing Tech Demo",
        type: "Tech Demo",
        date: "April 1, 2026",
        time: "3:00 PM",
        location: "Quantum Lab",
        price: 149.99,
        availableSeats: 40,
        image: "conventions.jpg",
        description: "Witness groundbreaking quantum computing demonstrations and applications."
    },
    {
        id: 20,
        title: "Fantasy Novel Launch & Signing",
        type: "Book Launch",
        date: "April 5, 2026",
        time: "5:00 PM",
        location: "Bibliophile Books",
        price: 29.99,
        availableSeats: 200,
        image: "exhibition.jpeg",
        description: "Join bestselling author for the launch of their latest fantasy novel with exclusive signing session."
    },
    {
        id: 21,
        title: "Future of AI Roundtable",
        type: "Industry Roundtable",
        date: "April 10, 2026",
        time: "1:00 PM",
        location: "Tech Institute",
        price: 299.99,
        availableSeats: 25,
        image: "tournaments.jpeg",
        description: "Intimate discussion with AI industry leaders about future trends and developments."
    },
    {
        id: 22,
        title: "Culinary Masterclass with Celebrity Chef",
        type: "Master Class",
        date: "April 15, 2026",
        time: "6:00 PM",
        location: "Gourmet Kitchen",
        price: 199.99,
        availableSeats: 30,
        image: "exhibition.jpeg",
        description: "Learn exclusive recipes and techniques from a renowned celebrity chef."
    }
];